<?php

namespace Qyk\Mm\Dao\Mysql\Lib\Module;
/**
 * mysql 操作结果
 * Class OpInserter
 * @package Qyk\Mm\Dao\Mysql\lib
 */
class InsertRt extends ModifyRt
{
    /**
     * 获取最近插入数据的主键编号
     * The mysqli_insert_id() function returns the ID generated by a query (usually INSERT) on a table with a column having the AUTO_INCREMENT attribute.
     * If no INSERT or UPDATE statements were sent via this connection, or if the modified table does not have a column with the AUTO_INCREMENT attribute,
     * this function will return zero.
     */
    public function getInsertId(): int
    {
        return mysqli_insert_id($this->dbLink);
    }
}

;