<?php

namespace Test;

use Qyk\Mm\Application;
use Qyk\Mm\Facade\Log;

/**
 * Class App
 * @package Test
 * @property Log $log
 */
class App extends Application
{
    protected function getProvider()
    {
        return parent::getProvider(); // TODO: Change the autogenerated stub
    }

}